# Generated by Django 4.0.1 on 2022-01-10 20:04

from datetime import timedelta

from django.db import migrations


def add_records(apps, schema_editor):

    student_model = apps.get_model('university', 'Student')
    student = student_model(first_name='Ivan', last_name='Ivanov')
    student.save()

    teacher_model = apps.get_model('university', 'Teacher')
    teacher = teacher_model(first_name='Petr', last_name='Vasiliev')
    teacher.save()

    hw_model = apps.get_model('university', 'Homework')
    django_hw = hw_model(text='Django ORM Homework',
                         deadline=timedelta(days=7))
    django_hw.save()

    hw_result_model = apps.get_model('university', 'HomeworkResult')
    hw_res = hw_result_model(author=student,
                             homework=django_hw,
                             solution='Django HW is done')
    hw_res.save()


def delete_records(apps, schema_editor):

    hw_result_model = apps.get_model('university', 'HomeworkResult')
    hw_res = hw_result_model.objects.filter(solution='Django HW is done').get()
    hw_res.delete()

    hw_model = apps.get_model('university', 'Homework')
    django_hw = hw_model.objects.filter(text='Django ORM Homework').get()
    django_hw.delete()

    teacher_model = apps.get_model('university', 'Teacher')
    teacher = teacher_model.objects.filter(first_name='Petr').get()
    teacher.delete()

    student_model = apps.get_model('university', 'Student')
    student = student_model.objects.filter(first_name='Ivan').get()
    student.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_records, delete_records),
    ]
